_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 19
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 1
dataset_path:
    value: /home/reid/projects/blast_waves/hdf5_dataset
device:
    value: cuda
epochs:
    value: 10
hidden_dim:
    value: 64
lr:
    value: 0.0001
num_layers:
    value: 4
patch_size:
    value: 3
patience:
    value: 10
run_name:
    value: lucid_blastformer_0
seq_len:
    value: 302
